# Site Settings
baseurl: ""
url : "https://fangwei.fun"
author: fw0x 

# Blog Settings
theme_settings :
  title : fw0x
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : fw0x
    description : Hi! I am a programmer. I like play guitar.
    experience :
      - start : 2018-07
        end : "?"
        experience : "/>:, Programmer"
      - start : 2012-01
        end : "2018-07"
        experience : "GIONEE, Programmer"        
    skills : 
      - skill : Java
        value : 85  # Percent value
      - skill : Distributed System
        value : 85
      - skill : Cloud Computing
        value : 80
        
  # Icons
  icons :
    email: fw0x@qq.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: fw0x
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
