# Site Settings
baseurl: ""
title: 方淡定
description: 独立思考
url : "https://fangwei.fun"

# Blog Settings
theme_settings :
  title : 方淡定
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : 方伟
    description : Hi! I am a programmer. I like play guitar.
    experience :
      - start : 2018-07
        end : "?"
        experience : "/>:, Programmer"
      - start : 2012-01
        end : "2018-07"
        experience : "GIONEE, Programmer"
    skills : 
      - skill : Java
        value : 85  # Percent value
      - skill : Distributed System
        value : 85
      - skill : Cloud Computing
        value : 75
        
  # Icons
  icons :
    email: fw0x@qq.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: fw0x
    gitlab: 
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  #disqus_shortname: fangwei-fun

# Post
excerpt_separator: <!--more-->

# Pagination
paginate: 5
paginate_path: "page/:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: 
  - jekyll-paginate
  - jekyll-feed
bootstrap:
  assets: true
